### PR TITLE
Upgrading to julia 0.4 and adding Float16 and BigFloat

### PR DESCRIPTION
**Pull request by ivanslapnicar**
Dear Simon, 

me and my colleague Nevena upgraded the file to work nice with Julia 0.4 (there is one warning remaining, I dont know how to get rid of it).
We also made two enhancements:
1. We use the package in another software where we also need Double{BigFloat}, which we implemented.
2. In order to be fully consistent, we also added Float16 support, so now all subtypes(AbstractFloat)
are covered. To that extent, maybe you should rename the package DoubleFloat or similar.

Regards, Ivan

### CODE REVIEW

**Comment by simonbyrne** [comment]
Thanks Ivan.

For BigFloats, wouldn't it be easier to just increase the precision? i.e. use `with_bigfloat_precision`?

**Comment by ivanslapnicar** [comment]
Simon,

you are right. Using `with_bigfloat_precision` is faster. Our application of `DoubleDouble.jl`
is in the package https://github.com/ivanslapnicar/Arrowhead.jl 
All files but one, use `Double{Float64}`.  In the file `arrowhead7.jl`, however, there are  several routines which are used to compute zeros of polynomials. There we essentially need to evaluate polynomial with Horner scheme in `Double` precision. So, having `DoubleDouble.jl` work with `BigFloat` makes those functions simpler (they just use multiple dispatch principle).

So, the proposal is to include `BigFloat` as one of the types in `DoubleDouble.jl`, but there should definitely be your comment that `with_bigfloat_precision` is faster.

What do you think?

Best, Ivan

**Comment by ivanslapnicar** [comment]
One more thing. There is a bug in line 100 of your master.

```
-{T<:BitsFloat}(x::Double{T}) = Double(-x.hi,-y.hi)
```

shoud read

```
-{T<:BitsFloat}(x::Double{T}) = Double(-x.hi,-x.lo)
```

Best, Ivan

**Comment by ivanslapnicar** [comment]
Simon,

on the second thought, I agree with you that it is the best  to leave `BigFloat` out of `DoubleDouble.jl`. I will make new function in `Arrowhead.jl` for  `BigFloat`. Can you make other changes in your package (especially the correction mentioned in the previous post, I get build erros in travis bacause of that).

Best, Ivan

**Comment by simonbyrne** [comment]
No worries, I'll try to get to it this week.

In some sense, double arithmetic is pointless for `Float16` or `Float32`, as you can promote to wider native types (`Float32` or `Float64` respectively): I don't know if this would be a better solution to your problem?

**Comment by ivanslapnicar** [comment]
Simon, 

the reason to support `Float16` and `Float32` is the same one for introducing those types in Julia in the first place. I am not using them, but that might be useful for people developing algorithms which work in those precisions. I can imagine that someone using 2-byte or 4-byte floats on some special processor, might find `Double{Float16}` or `Double{Float32}` handy, at least for some development.

Best, Ivan

**Comment by dpsanders** [comment]
Could this please be merged? I was just trying out the package on 0.4.5 and getting some errors.

**Comment by simonbyrne** [comment]
Sorry, this slipped completely off my radar. Done.

**Comment by dpsanders** [comment]
Thanks!

**Comment by dpsanders** [comment]
@ivanslapnicar I now get this on 0.4:
```julia
julia> double(pi)
DoubleDouble.Double{BigFloat}(3.141592653589793238462643383279502884197169399375105820974944592307816406286198,0.000000000000000000000000000000000000000000000000000000000000000000000000000000)
```
whereas I want to create a `Double{Float64}`.

**Comment by simonbyrne** [comment]
I've just pushed an update to fix that.

@dpsanders by the way, I've given you commit access, if you need to make further changes.

**Comment by dpsanders** [comment]
Confirmed working, thanks! And thanks for the commit access.

**Pull request merged**
